In [1]:
from Utils import Util
from Agent import Agent
from Env import Env
import numpy as np
import torch.nn as nn
import torch
import numpy as np


numEpoch = 30
k = 10
windowSize = 2

util = Util()
graph, embedding, graph_size, top_nodes, node2neighbors, idx2node, node2idx = util.load_dataset("./dataset/", 10, 0.003)

In [2]:
embedding2 = nn.Embedding(363, 2)
embedding2.weight = nn.Parameter(torch.from_numpy(embedding))
embedding2.weight.requires_grad = False

In [26]:
new_embedding = torch.from_numpy(embedding)
print(new_embedding.size())

torch.Size([363, 2])


In [50]:
lin1 = nn.Linear(2, 2+1)
lin2 = nn.Linear(2, 2+1)
lin3 = nn.Linear(2, 2+1)
lin4 = nn.Linear(3 *(2 + 1), 1)


seeds_idx = torch.tensor([1,2,4,5])
candidates_idx = torch.tensor([6,7,8,9,10,11,12,23,45,34])

seeds_emb = embedding2(seeds_idx).float()
candidates_emb = embedding2(candidates_idx).float()

seeds_max,_ = torch.max(seeds_emb, 0)
candidates_max,_ = torch.max(candidates_emb, 0)

seeds_max_list = torch.stack([seeds_max.clone() for i in range(10)], 0)
candidates_max_list = torch.stack([candidates_max.clone() for i in range(10)], 0)

Cat = torch.cat((lin1(candidates_max_list), lin2(seeds_max_list), lin3(candidates_emb)), dim = 1)
Q = lin4(Cat).reshape(10)

In [48]:
print(Q.reshape(10))
# finalQ = torch.cat(Q)

tensor([0.5449, 0.6461, 0.5137, 0.5112, 0.5321, 0.6705, 0.5795, 0.3295, 0.6496,
        0.5954], grad_fn=<ViewBackward>)


In [3]:
test1 = torch.tensor([[1],[2],[3]])
test2 = torch.tensor([[1],[2],[3]])


In [9]:
action = np.random.choice([111,222,333,444,423,345,1236], size=1)
action

array([423])

In [4]:
import torch
data1 = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
data2 = torch.tensor([[1,2],[3,4],[5,6],[7,8]])

data3 = torch.nn.ReLU()(torch.cat((data1, data2), dim=1))
print(data3)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [5, 6, 5, 6],
        [7, 8, 7, 8]])


In [ ]:
加载图
构造数据结构
node2weight
in_neighbors
out_neighbors